services:
  - type: web
    name: snehulak-smile-dental-clinic
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.lwobdoiayyikpzfzpoqq:mypassword123@aws-1-eu-west-2.pooler.supabase.com:6543/postgres"
